### ISSUE TITLE
API Reference - using both data and store

### ISSUE THREAD

**Issue by jngbsn** [cferdinandi/reef-js#9]
I'm assuming since v10 this is no longer true?
https://github.com/cferdinandi/reef-js/blob/46dc308b15aacb7b86598529d33125be39452c86/content/api.md?plain=1#L163

**Comment by cferdinandi** [comment]
Ohh yep! Good catch!

**Comment by cferdinandi** [comment]
Just pushed a fix. Thanks for letting me know.
